'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight, Check, Mail, MoveUpRight } from 'lucide-react'
import { experience, profile, projects, skills, socials } from '@/lib/portfolio-data'
import { fadeUp, scrollToSection } from '@/lib/portfolio-utils'

export function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div> }

export function Hero() { return <section id="home" className="hero section-wrap"><motion.div initial="hidden" animate="visible" variants={fadeUp} className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Available for select projects</p><h1>Designing digital <em>experiences</em> with clarity.</h1><p className="hero-sub">{profile.tagline}</p><div className="hero-actions"><button className="button button-dark" onClick={() => scrollToSection('#projects')}>View projects <ArrowUpRight size={17} /></button><button className="button button-glass" onClick={() => scrollToSection('#contact')}>Get in touch <Mail size={16} /></button></div></motion.div><motion.div initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .8, delay: .15 }} className="hero-art"><div className="portrait-frame"><img src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85" alt="Portrait of Alex Morgan" /></div><div className="art-caption"><span>AM / 2026</span><span>NYC — 40.7128° N</span></div></motion.div></section> }

export function About() { return <section id="about" className="section-wrap section-block"><SectionHeading eyebrow="01 / About" title="A thoughtful mix of logic and instinct." /><div className="about-grid"><div className="about-lede"><p>{profile.bio}</p><a className="text-link" href={`mailto:${profile.email}`}>More about me <ArrowUpRight size={16} /></a></div><div className="skills-panel"><p className="eyebrow">Capabilities</p><div className="skill-grid">{skills.map((skill) => <span className="skill-chip" key={skill}>{skill}</span>)}</div></div></div></section> }

export function Projects() { return <section id="projects" className="section-wrap section-block"><SectionHeading eyebrow="02 / Selected work" title="A few things I&apos;ve made." /><div className="project-grid">{projects.map((project, i) => <motion.article initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }} variants={fadeUp} transition={{ delay: i * .08 }} className={`project-card ${project.featured ? 'featured' : ''}`} key={project.title}><div className="project-image"><img src={project.image} alt={`${project.title} project preview`} /><a href={project.live} aria-label={`View ${project.title}`} className="image-arrow"><ArrowUpRight size={19} /></a></div><div className="project-info"><div><p className="project-kicker">0{i + 1} — {project.tags.join(' / ')}</p><h3>{project.title}</h3><p>{project.description}</p></div><a href={project.github} className="project-link">View case study <MoveUpRight size={15} /></a></div></motion.article>)}</div></section> }

export function Experience() { return <section id="experience" className="section-wrap section-block"><SectionHeading eyebrow="03 / Experience" title="The path so far." /><div className="timeline">{experience.map((item) => <div className="timeline-item" key={item.period}><div className="timeline-date">{item.period}</div><div className="timeline-dot" /><div className="timeline-content"><h3>{item.role}</h3><p className="company">{item.company}</p><p>{item.description}</p></div></div>)}</div></section> }

export function Contact() { const [sent, setSent] = useState(false); return <section id="contact" className="section-wrap contact-section section-block"><div className="contact-copy"><p className="eyebrow">04 / Contact</p><h2>Have a good idea?<br /><em>Let&apos;s make it real.</em></h2><p>I&apos;m currently available for select freelance collaborations and product design roles.</p><div className="social-list">{socials.map((social) => <a href={social.href} key={social.label}>{social.label} <ArrowUpRight size={15} /></a>)}</div></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true) }}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@company.com" /></label><label>Message<textarea required name="message" rows={4} placeholder="Tell me a little about your project..." /></label><button className="button button-dark" type="submit">{sent ? <>Message sent <Check size={16} /></> : <>Send message <ArrowUpRight size={16} /></>}</button></form></section> }

export function Footer() { return <footer className="footer section-wrap"><span>© 2026 {profile.name}</span><span>Designed & built with intention.</span><a href="#home">Back to top ↑</a></footer> }
